# Production environment override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  bind:
    # Production-specific configuration
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1.0'
        reservations:
          memory: 512m
          cpus: '0.5'
    # Production health checks
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "localhost", "+timeout=5"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    # Security labels
    labels:
      - "com.dns-server.environment=production"
      - "com.dns-server.security.level=high"
      - "com.dns-server.backup=enabled"

  # Optional: Add monitoring services for production
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: dns-prometheus
  #   restart: unless-stopped
  #   ports:
  #     - "${PROMETHEUS_PORT}:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - dns-network
  #   depends_on:
  #     - bind

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: dns-grafana
  #   restart: unless-stopped
  #   ports:
  #     - "${GRAFANA_PORT}:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  #   networks:
  #     - dns-network
  #   depends_on:
  #     - monitoring

# volumes:
#   grafana-storage:
