# Helm values for external-dns with BIND DNS (RFC2136) provider
# Chart: https://kubernetes-sigs.github.io/external-dns/
# Usage: helm install external-dns external-dns/external-dns -f external-dns-values.yaml

# Global configuration
fullnameOverride: "external-dns"
nameOverride: "external-dns"

# Image configuration
image:
  registry: registry.k8s.io
  repository: external-dns/external-dns
  tag: "v0.14.0"
  pullPolicy: IfNotPresent

# Deployment configuration
replicaCount: 1
deploymentStrategy:
  type: Recreate

# External-DNS provider configuration
provider: rfc2136

# RFC2136 (BIND DNS) specific configuration
rfc2136:
  # BIND DNS server connection
  host: "bind-dns-server.dns-system.svc.cluster.local"  # Kubernetes service name
  port: 53
  zone: "k8s.local"  # Zone to manage
  
  # TSIG authentication
  tsigKeyname: "tsig-key"
  tsigSecret: ""  # Will be set via secret
  tsigSecretAlg: "hmac-sha256"
  tsigAxfr: true
  
  # Advanced options
  minTTL: 0s
  axfrTimeout: 10s

# Domain filtering
domainFilters:
  - "k8s.local"
  - "*.k8s.local"

# Zone filtering (optional)
zoneNameFilters: []
zoneIdFilters: []

# Annotation filtering
annotationFilter: "external-dns.alpha.kubernetes.io/hostname"

# Source configuration
sources:
  - service
  - ingress
  - istio-gateway
  - istio-virtualservice

# Registry configuration for tracking DNS records
registry: "txt"
txtOwnerId: "external-dns-k8s"
txtPrefix: "external-dns-"
txtSuffix: ""

# Policy configuration
policy: "sync"  # Options: sync, upsert-only, create-only

# Logging configuration
logLevel: "info"
logFormat: "text"

# Synchronization settings
interval: "1m"
triggerLoopOnEvent: false

# Metrics and monitoring
metrics:
  enabled: true
  port: 7979
  
serviceMonitor:
  enabled: true
  namespace: ""
  interval: 30s
  scrapeTimeout: 10s
  labels: {}

# Security context
securityContext:
  fsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
      - ALL

# Resource configuration
resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Service account
serviceAccount:
  create: true
  name: "external-dns"
  annotations: {}

# RBAC
rbac:
  create: true
  apiVersion: v1

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7979"
  prometheus.io/path: "/metrics"

# Pod labels
podLabels:
  app.kubernetes.io/component: "dns-controller"

# Environment variables
env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-tsig-secret
        key: tsig-secret

# Extra arguments (in addition to the generated ones)
extraArgs:
  - --events
  - --source=service
  - --source=ingress

# Extra volumes and mounts
extraVolumes: []
extraVolumeMounts: []

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Deployment annotations
deploymentAnnotations: {}

# Service configuration
service:
  enabled: true
  type: ClusterIP
  port: 7979
  annotations: {}

# Priorityclass
priorityClassName: ""

# DNS configuration
dnsPolicy: "Default"
dnsConfig: {}

# Termination grace period
terminationGracePeriodSeconds: 30
