---
# Example Service with external-dns annotation
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.k8s.local
    external-dns.alpha.kubernetes.io/ttl: "300"
  labels:
    app: nginx
    environment: test
spec:
  type: LoadBalancer  # or ClusterIP if using with Ingress
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx

---
# Example Deployment for nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi

---
# Example Ingress with external-dns annotation
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web.k8s.local,app.k8s.local
    external-dns.alpha.kubernetes.io/ttl: "300"
    # Add your ingress controller annotations here
    # nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: nginx
spec:
  rules:
    - host: web.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
    - host: app.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

---
# Example Service with multiple hostnames
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.k8s.local,api-v1.k8s.local,rest.k8s.local
    external-dns.alpha.kubernetes.io/ttl: "600"
  labels:
    app: api
    tier: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: api

---
# Example Deployment for API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: httpd:2.4
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

---
# Example Service with custom annotations
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: db.k8s.local
    external-dns.alpha.kubernetes.io/ttl: "3600"
    external-dns.alpha.kubernetes.io/target: "database-cluster.k8s.local"  # CNAME target
  labels:
    app: database
    tier: data
spec:
  type: ExternalName
  externalName: postgres.internal.company.com  # External database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
